name: CI
on: [push]
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:

  test:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    container: unityci/editor:2018.4.15f1-base-0.9.0
    strategy:
      matrix:
        testMode:
        - EditMode
        - PlayMode
    steps:

    - name: Checkout Project
      uses: actions/checkout@v1
      with:
        lfs: true

    - name: Restore Library from cache
      uses: actions/cache@v2
      with:
        path: Library
        key: Library-base

    - name: Activate Unity
      run: |
        echo "$UNITY_LICENSE" > /Unity_v2018.x.ulf

        unity-editor \
        -batchmode -nographics -quit -logFile \
        -manualLicenseFile /Unity_v2018.x.ulf || true

        rm /Unity_v2018.x.ulf

    - name: Run ${{ matrix.testMode }} tests
      shell: sh {0}
      run: |
        xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
        unity-editor \
        -batchmode -logFile \
        -projectPath . \
        -runTests -testPlatform ${{ matrix.testMode }} \
        -testResults Builds/TestResults-${{ matrix.testMode }}.xml

        UNITY_EXIT_CODE=$?

        if [ $UNITY_EXIT_CODE -eq 0 ]; then
          cat Builds/TestResults-${{ matrix.testMode }}.xml | grep test-run  | grep result
          echo "Run succeeded, no failures occurred"
        elif [ $UNITY_EXIT_CODE -eq 2 ]; then
          cat Builds/TestResults-${{ matrix.testMode }}.xml | grep test-run  | grep Failed
          cat Builds/TestResults-${{ matrix.testMode }}.xml | grep test-case | grep Failed
          echo "Run succeeded, some tests failed"
        elif [ $UNITY_EXIT_CODE -eq 3 ]; then
          echo "Run failure (other failure)"
        else
          echo "Unexpected exit code $UNITY_EXIT_CODE"
        fi

        exit $UNITY_EXIT_CODE

    - name: Upload ${{ matrix.testMode }} test results
      uses: actions/upload-artifact@v2
      with:
        name: TestResults-${{ matrix.testMode }}.xml
        path: Builds/TestResults-${{ matrix.testMode }}.xml

  build-unitypackage:
    needs: test
    name: Build unitypackage
    runs-on: ubuntu-latest
    container: unityci/editor:2018.4.15f1-base-0.9.0
    steps:

    - name: Checkout Project
      uses: actions/checkout@v1
      with:
        lfs: true

    - name: Restore Library from cache
      uses: actions/cache@v2
      with:
        path: Library
        key: Library-base

    - name: Activate Unity
      run: |
        echo "$UNITY_LICENSE" > /Unity_v2018.x.ulf

        unity-editor \
        -batchmode -nographics -quit -logFile \
        -manualLicenseFile /Unity_v2018.x.ulf || true

        rm /Unity_v2018.x.ulf

    - name: Build unitypackage
      run: |
        mkdir -p Builds

        unity-editor \
        -batchmode -nographics -quit -logFile \
        -projectPath . \
        -exportPackage \
        Assets/Scripts/ColorHash.cs \
        Builds/ColorHash.unitypackage

    - name: Upload unitypackage
      uses: actions/upload-artifact@v2
      with:
        name: ColorHash.unitypackage
        path: Builds/ColorHash.unitypackage

  build-windows:
    needs: test
    name: Build for Windows
    runs-on: ubuntu-latest
    container: unityci/editor:2018.4.15f1-windows-mono-0.9.0
    steps:

    - name: Checkout Project
      uses: actions/checkout@v1
      with:
        lfs: true

    - name: Restore Library from cache
      uses: actions/cache@v2
      with:
        path: Library
        key: Library-windows

    - name: Activate Unity
      run: |
        echo "$UNITY_LICENSE" > /Unity_v2018.x.ulf

        unity-editor \
        -batchmode -nographics -quit -logFile \
        -manualLicenseFile /Unity_v2018.x.ulf || true

        rm /Unity_v2018.x.ulf

    - name: Build Win64
      run: |
        xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
        unity-editor \
        -batchmode -quit -logFile \
        -projectPath . \
        -buildTarget Win64 \
        -buildWindows64Player Builds/Win64/UnityCI.exe

    - name: Upload Win64
      uses: actions/upload-artifact@v2
      with:
        name: Build-Win64
        path: Builds/Win64

  build-android:
    needs: test
    name: Build for Android
    runs-on: ubuntu-latest
    container: unityci/editor:2018.4.15f1-android-0.9.0
    steps:

    - name: Checkout Project
      uses: actions/checkout@v1
      with:
        lfs: true

    - name: Restore Library from cache
      uses: actions/cache@v2
      with:
        path: Library
        key: Library-android

    - name: Activate Unity
      run: |
        echo "$UNITY_LICENSE" > /Unity_v2018.x.ulf

        unity-editor \
        -batchmode -nographics -quit -logFile \
        -manualLicenseFile /Unity_v2018.x.ulf || true

        rm /Unity_v2018.x.ulf

    - name: Build Android
      run: |
        xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
        unity-editor \
        -batchmode -quit -logFile \
        -projectPath . \
        -buildTarget Android \
        -executeMethod UnityPlayerBuilder.BuildAndroid \
        -customBuildPath Builds/Android/UnityCI.apk

    - name: Upload Android
      uses: actions/upload-artifact@v2
      with:
        name: Build-Android.apk
        path: Builds/Android/UnityCI.apk
